name: Java CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
      - run: mvn --batch-mode --update-snapshots verify
      - run: mkdir staging && cp target/uber*.jar staging
      - uses: actions/upload-artifact@v3
        with:
          name: Package
          path: staging

  release:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Release new version
        run: |
          git config --global user.email "peter.pivarnik@gmail.com"
          git config --global user.name "peterpivarnik"
          mvn -B release:prepare
          mvn release:perform -Darguments="-Dmaven.deploy.skip=true"
