name: Java CI

on: [ push ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'adopt'
      - name: Build with tests
        run: mvn --batch-mode --update-snapshots verify
      - uses: actions/checkout@v2
      - name: Release prepare
        run: |
          git config --global user.email "${{ secrets.USER_EMAIL }}"
          git config --global user.name "${{ secrets.USER_NAME }}"
          mvn -B release:prepare
      - uses: actions/upload-artifact@v3
        with:
          name: Package
          path: staging
      - name: Copy target files
        run: mkdir staging && cp target/${{ secrets.TARGET_FILE_NAME }} staging
      - name: Upload to S3
        run: |
          aws s3 cp target/${{ secrets.TARGET_FILE_NAME }} s3://${{ secrets.AWS_S3_BUCKET }}
          aws lambda update-function-code \
          --function-name ${{ secrets.AWS_LAMBDA_FUNCTION_NAME }} \
          --s3-bucket ${{ secrets.AWS_S3_BUCKET }} \
          --s3-key ${{ secrets.TARGET_FILE_NAME }}
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: ${{ secrets.AWS_REGION }}
      - name: Release perform
        run: |
          mvn release:perform -Darguments="-Dmaven.deploy.skip=true"