name: Java CI

on: [ push ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
      - run: mvn --batch-mode --update-snapshots verify

      - uses: actions/checkout@v2
      - name: Release new version
        run: |
          git config --global user.email "${{ secrets.USER_EMAIL }}"
          git config --global user.name "${{ secrets.USER_NAME }}"
          mvn -B release:prepare
          mvn release:perform -Darguments="-Dmaven.deploy.skip=true"
      - run: mkdir staging && cp target/uber*.jar staging
      - uses: actions/upload-artifact@v3
        with:
          name: Package
          path: staging

      - uses: actions/checkout@master
      - name: Upload to S3
        run: |
          aws s3 cp/home/runner/work/crypto-trade-analyser/crypto-trade-analyser/target/checkout/target/uber-crypto-trader-*.jar s3://${{ secrets.S3_BUCKET }}
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: ${{ secrets.S3_BUCKET_REGION }}


