name: Java CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
      - name: Build with Maven
      - run: mvn --batch-mode --update-snapshots verify

  release:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - run: |
          git config --global user.email "peter.pivarnik@gmail.com"
          git config --global user.name "peterpivarnik"
          mvn -B release:prepare
          mvn release:perform

  install:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/upload-artifact@v3
        with:
          name: Package
          path: staging
      - run: mkdir staging && cp target/*.jar staging

